name: Deploy Dist

on: [push, workflow_dispatch]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node 20
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Print Node Version
        run: node -v

      - name: Install Dependencies
        working-directory: starter-code-cicd
        run: npm ci

      - name: Run Tests
        working-directory: starter-code-cicd
        run: npm run test
        
