name: Deploy Dist

on: [push, workflow_dispatch]

jobs:
  greet:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter-code-cicd

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node 20
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Debug Files
        run: ls

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
